name: .NET Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.203'

      - name: Read version from file
        id: read-version
        run: |
          version=$(cat version.txt)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build
        run: dotnet build src/ --configuration Release
        
      - name: Test
        run: dotnet test src/ --configuration Release --no-build
        
      - name: Pkg
        run: dotnet pack --configuration Release --no-build --no-restore --output nupkg --version-suffix $VERSION ./src/
        
      - name: Publish NuGet package
        run: dotnet nuget push ./nupkg/ --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_XO }}

